### ISSUE TITLE
Add text labels to arrows

### ISSUE THREAD

**Issue by nrennie** [nrennie/ggflowchart#15]
- add a column `label` to `data` (default `NULL`)
- add labels next to edges
- positioning (based on version 1.0.0) is easy, e.g. put them to the left/right
- might need to think about position of text a bit more when thinking about more arrow options - see #5 

Feature request from Fosstodon: https://fosstodon.org/@frod_san@ecoevo.social/110373342711057144

**Comment by nrennie** [comment]
Addressed in version 1.0.0.9000 (2023_05_19). Will be in CRAN version 1.0.1.

**Comment by Pakillo** [comment]
Thanks a lot!
