### ISSUE TITLE
Example Code does not work

### ISSUE THREAD

**Issue by jimewu** [nrennie/ggflowchart#34]
With regard to the example from [here](https://nrennie.github.io/ggflowchart/articles/layout-options.html), I tried to run the code as the following"

```r
lapply(
    c(
        "dplyr",
        "ggplot2",
        "ggflowchart"
    ),
    library,
    character.only = TRUE
)

data <- tibble::tribble(
  ~from, ~to,
  "A", "B",
  "B", "C"
)

node_data <- tibble::tribble(
  ~name, ~x, ~y,
  "A", 1, 3,
  "B", 2, 2,
  "C", 3, 1
)

ggflowchart(data, node_data = node_data, layout = "custom")
```
the first error I got was about the "layout = "custom" is unused. So I removed it and ran:

```r
ggflowchart(data, node_data = node_data)
```

However, I got the following error message:

```
Error in `dplyr::mutate()`:
ℹ In argument: `xmin = .data$x - x_nudge`.
Caused by error in `.data$x`:
! Column `x` not found in `.data`.
Run `rlang::last_trace()` to see where the error occurred.
```

The further message by running `rlang::last_trace()` as suggested above was:

```
<error/dplyr:::mutate_error>
Error in `dplyr::mutate()`:
ℹ In argument: `xmin = .data$x - x_nudge`.
Caused by error in `.data$x`:
! Column `x` not found in `.data`.
---
Backtrace:
     ▆
  1. ├─ggflowchart::ggflowchart(data, node_data = node_data)
  2. │ └─ggflowchart:::get_nodes(...)
  3. │   └─node_layout %>% ...
  4. ├─dplyr::mutate(...)
  5. ├─dplyr:::mutate.data.frame(...)
  6. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  7. │   ├─base::withCallingHandlers(...)
  8. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  9. │     └─mask$eval_all_mutate(quo)
 10. │       └─dplyr (local) eval()
 11. ├─x
 12. ├─rlang:::`$.rlang_data_pronoun`(.data, x)
 13. │ └─rlang:::data_pronoun_get(...)
 14. └─rlang:::abort_data_pronoun(x, call = y)
```

Any suggestions please?

**Comment by nrennie** [comment]
Which version of ggflowchart are you using? Have you installed the development version, or the version from CRAN? The layout argument is only available in the development version on GitHub at he moment - see the README for installation instructions.

**Comment by jimewu** [comment]
The version of ggflowchart I used was 'ggflowchart_1.0.0' as returned by `sessionInfo()`. The example worked after I installed the github version 'ggflowchart_1.0.0.9006'. I am sorry that I missed the information that the layout argument is only available in the  github version. Thanks for your help.
