### ISSUE TITLE
Support for same-level arrows

### ISSUE THREAD

**Issue by nrennie** [nrennie/ggflowchart#5]
Need to edit the `get_edges()` function. Currently, same-level edges cross over existing boxes depending on which one appears first in the data set. Need some if statements based on y-coordinates (also check #1).

Currently: 
![issue5](https://user-images.githubusercontent.com/42338476/182265794-eea16688-7e8e-47a3-a5c8-ddffc0288d68.png)

**Comment by nrennie** [comment]
@laresbernardo If you install the development version from GitHub using `remotes::install_github("nrennie/ggflowchart")`, the lateral arrows issue should be fixed with this PR (see example in #25 for how it's changed).

**Comment by laresbernardo** [comment]
Just got the notification from this thread, fantastic! Will give it a go. Good work here! :)
